server {
    listen 80;
    listen [::]:80;
    server_name www.milaskoltukyikama.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    return 301 https://milaskoltukyikama.com$request_uri;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    return 301 https://$host$request_uri;
}
