server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate /etc/nginx/ssl/default.crt;
    ssl_certificate_key /etc/nginx/ssl/default.key;

    root /var/www/html;

    # Default olarak her şeyi 404 yap
    location / {
        return 404;
    }

    # Dizin listeleme yok, index yok
    location = /my-files-local/ {
        return 404;
    }

    # Altındaki dosyalara path ile erişilebilir
    location /my-files-local/ {
        autoindex off;
        try_files $uri =404;
    }

    location ~ /\.ht {
        deny all;
    }
}